//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BEEUTaller1
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Pelicula
    {
        public int idpelicula { get; set; }

        [DataType(DataType.Text)]
        [Required(ErrorMessage = "El nombre es requeridos"), MaxLength(55)]
        [Display(Name = "Nombre pelicula")]
        public string nombre { get; set; }

        [Display(Name = "Fecha de lanzamiento")]
        [DisplayFormat(DataFormatString = "{0:dd/MMM/yyyy}")]
        [DataType(DataType.Date)]
        public Nullable<System.DateTime> fecha_lanzamiento { get; set; }

        [DataType(DataType.Text)]
        [Required(ErrorMessage = "La categoria es requerida"), MaxLength(15)]
        [Display(Name = "Categoria de la pelicula")]
        public string categoria { get; set; }

        [DataType(DataType.Text)]
        [Required(ErrorMessage = "La duracion es requerida"), MaxLength(55)]
        [Display(Name = "Duracion de la pelicula en minutos")]
        public string duracion { get; set; }
    }
}
